#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================


# file path: ~/SpaceVim.d/init.toml


# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
  colorscheme = "onedark"
  colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
  enable_guicolors = false
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  statusline_unicode = false
# Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = true
  autocomplete_method = 'coc'
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'checkers'
  lint_on_save = false

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'format'

[[layers]]
  name = 'lang#python'


[[layers]]
  name = 'lsp'
  filetypes = ['c', 'cpp']
  enabled_clients = ['clangd']

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c++20"
    c = "c17"
[[layers]]
  name = 'chinese'

[[layers]]
  name = 'lang#latex'

